// <auto-generated />
using EmployeeAPI.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260711111500_AddLegalCategoryForeignKeyToActMasterSQL")]
    partial class AddLegalCategoryForeignKeyToActMasterSQL
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");
            // Model configuration here (placeholder - actual model building happens in AppDbContextModelSnapshot)
#pragma warning restore 612, 618
        }
    }
}
